# cmalign
#
# VERSION               golob/infernal:1.1.2_bcw_0.2.0

FROM      alpine:3.7
RUN mkdir /fh && mkdir /app
RUN mkdir -p /mnt/inputs/file && mkdir -p /mnt/outputs/file && mkdir /scratch
RUN apk add --no-cache python3==3.6.3-r9 bash make gcc build-base
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN pip3 install boto3 awscli bucket_command_wrapper==0.2.0

# CMALIGN stuff

RUN mkdir /cmalign && mkdir /cmalign/src && mkdir /cmalign/data
WORKDIR /cmalign/src
RUN wget http://eddylab.org/infernal/infernal-1.1.2.tar.gz
RUN tar xzvf infernal-1.1.2.tar.gz
WORKDIR /cmalign/src/infernal-1.1.2
RUN ./configure
RUN make && make install
WORKDIR /cmalign/src/infernal-1.1.2/easel
RUN make install
WORKDIR /cmalign/src/infernal-1.1.2/hmmer
RUN make install
RUN wget http://rfam.xfam.org/family/RF00177/cm -O /cmalign/data/SSU_rRNA_bacteria.cm

# Cleanup
WORKDIR /cmalign
RUN rm -R /cmalign/src
RUN apk del build-base gcc make