name: Docker Image CI

on:
  push:
    tags: 
      - "barcodecop*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file barcodecop/Dockerfile --tag barcodecop:$(date +%s)
